# Generated by Django 4.2.6 on 2023-10-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('img', models.ImageField(upload_to='index/img')),
                ('price', models.IntegerField()),
                ('bio', models.TextField()),
            ],
        ),
    ]
