# Generated by Django 4.2.6 on 2023-10-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_lates'),
    ]

    operations = [
        migrations.AddField(
            model_name='lates',
            name='nomi',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
