# Generated by Django 4.2.6 on 2023-10-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_lates_nomi'),
    ]

    operations = [
        migrations.AddField(
            model_name='lates',
            name='bio',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lates',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
